steps:
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '--build-arg'
  - 'SONARQUBE_SCANNER_CLI_VERSION=3.3.0.1492'
  - '-t'
  - 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
  - '-t'
  - 'gcr.io/$PROJECT_ID/sonar-scanner:3.3.0.1492'
  - '.'

images: 
- 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
- 'gcr.io/$PROJECT_ID/sonar-scanner:3.3.0.1492'

tags: ['cloud-builders-community']
